name: 'ECR to DockerHub Replication'
description: 'ECR to DockerHub Replication'
author: 'Romar Cablao'
inputs:
  dockerhub_user:
    description: 'Dockerhub User'
    required: true
  dockerhub_token:
    description: 'Dockerhub Token'
    required: true
  dockerhub_image_prefix:
    description: 'Dockerhub Image Prefix'
    required: true
  aws_container_registry:
    description: 'AWS Container Registry'
    required: true
  container_image_name:
    description: 'Container Image Name'
    required: true
  container_image_version:
    description: 'Container Image Version'
    required: true
  aws_access_key:
    description: 'AWS Access Key'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
outputs:
  app_version:
    description: 'App version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerhub_user }} 
    - ${{ inputs.dockerhub_token }}
    - ${{ inputs.dockerhub_image_prefix }}
    - ${{ inputs.aws_container_registry }}
    - ${{ inputs.container_image_name }}
    - ${{ inputs.container_image_version }}
    - ${{ inputs.aws_access_key }}
    - ${{ inputs.aws_secret_access_key }}
    - ${{ inputs.aws_region }}